### ISSUE TITLE
parsing the url with host returns no host

### ISSUE THREAD

**Issue by bpawan** [zendframework/zend-uri#32]
I am not sure if this is expected or is a problem. 
For example when I use a example url like :

```
$uri = UriFactory::factory('www.test.de/test/bild1.jpg');
echo $uri->getHost();
```

I was would expecting it to actually get the host i.e. `www.test.de` but get `null` instead. 

Can this be a bug or am I missing something?

**Comment by Xerkus** [comment]
It is because `www.test.de/test/bild1.jpg` is a relative url but not a valid relative url *with authority*. `www.test.de` here is just a part of the path.
Valid format for that url would be `//www.test.de/test/bild1.jpg`

Confusion can stem from the browser location bar, where user input is fixed to a proper url if first path segment looks like a valid hostname since browser does not accept path relative url there.

Please see https://tools.ietf.org/html/rfc3986#section-3.2
>  The authority component is preceded by a double slash ("//") and is
   terminated by the next slash ("/"), question mark ("?"), or number
   sign ("#") character, or by the end of the URI.
